### ISSUE TITLE
skips the first # during countdown on all sets

### ISSUE THREAD

**Issue by HosAkh** [JonFranklin301/interval-timer#3]
When we set the timer to say 10 seconds with 15 seconds rest period the timer starts but it goes from 10 to 8 then 7,6,5...
and same with rest period: 15, 13, 12,11,10...

we have tried it with all different kinds of increments of numbers.
ran it as a built project and installed it on different phones just in case it was lag on simulators. 

Ran through our code and nothing we can find on our end that is causing the initial jump. If you even say run for 5 sets on every set, for every number, it skips the first number and then runs normally.

**Comment by JonFranklin301** [comment]
@BeyoncesHomeboy can you provide an example of how you're implement it?

**Comment by JonFranklin301** [comment]
@BeyoncesHomeboy  Having done some testing (I think ) I am seeing see the issue you are having.

The timer is showing the correct time. Starting at 20.000 seconds, counting down with a 1000ms interval, you would expect to see 19.000 however because javascript is not perfect it is taking 1001ms to execute (for example), therefore the exact time ends up being 18.999. When displaying only seconds it would look like it is jumping from 20 to 18.

On a count-up timer this is usually not an issue as you will see the correct second, but this is more apparent when using a count-down timer and when only displaying seconds, it can look like the incorrect time.
To solve this I would either use a faster `updateFrequency` of 100ms (or faster), or round the seconds+milliseconds to the nearest second by doing: `Math.round((time.millisecondsTotal / 1000) % 60)` or `Math.round(parseFloat(time.seconds + '.' + time.milliseconds))`

Please see this pen for example: https://codepen.io/JonFranklin301/pen/WNpzqPX

**Comment by JonFranklin301** [comment]
Following on from further testing, using `Math.round((time.millisecondsTotal / 1000) % 60)` resulted in outputs such as `9:60` instead of  `10:00`.

To correct this the seconds should be rounded before remainder 60: `Math.round(time.millisecondsTotal / 1000) % 60`
This corrects the seconds from `60` to `0`, however the timer would now read `9:00` instead of `10:00`

To correct the minutes, again round the seconds then calculate the minutes based off this., `Math.floor(Math.round(time.millisecondsTotal / 1000) / 60)`
The timer would now correctly read `10:00`

example usage: 
```js
  var time = timer.getTime;

  var secondsTotalRounded = Math.round(time.millisecondsTotal / 1000);
  var seconds             = secondsTotalRounded % 60;
  var minutesTotal        = Math.floor(secondsTotalRounded / 60);
  // var minutes             = Math.floor(secondsTotalRounded / 60) % 60;
  // The same logic applies for hours...

  var timeText = intervalTimer.pad('00', minutesTotal, true) + ':' + intervalTimer.pad('00', seconds, true);
```

It's tough to expect the user to implement this however if these calculation changes are implemented in the module for countdown timer, it would no longer be time-accurate (?). 
For example with 1 second left on a timer you would want it to display `00:01` however the exact time is `0.991`, so technically it's `0` seconds and `991` milliseconds.
Need to think about the best way of implementing this, perhaps a `timer.getTimeFriendly` method that returns friendly times, or a config option that changes the return values from precise to friendly.
